services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rlaeh984020!
      MYSQL_DATABASE: cicd_test
    ports:
      - "3306:3306"